// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNH1S1_NE02d6LzS3Gn4Nio6ef2Jtf6u0',
    appId: '1:51232428753:web:4f0c3fda038d2e1f6bebf0',
    messagingSenderId: '51232428753',
    projectId: 'shingu-3aced',
    authDomain: 'shingu-3aced.firebaseapp.com',
    storageBucket: 'shingu-3aced.firebasestorage.app',
    measurementId: 'G-Z0T76TZPJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkuEAtKOpHScBMKCDTvkaOFKEmRrjCikY',
    appId: '1:51232428753:android:de62c7bea0f72ca06bebf0',
    messagingSenderId: '51232428753',
    projectId: 'shingu-3aced',
    storageBucket: 'shingu-3aced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKM4QWqLJzFnbvWf4xNqRHjwoCgcbzTTA',
    appId: '1:51232428753:ios:ebbbc03ffa8be6086bebf0',
    messagingSenderId: '51232428753',
    projectId: 'shingu-3aced',
    storageBucket: 'shingu-3aced.firebasestorage.app',
    iosClientId: '51232428753-2s3d7hdau9e9ea85504s6juiu1omq8o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKM4QWqLJzFnbvWf4xNqRHjwoCgcbzTTA',
    appId: '1:51232428753:ios:ebbbc03ffa8be6086bebf0',
    messagingSenderId: '51232428753',
    projectId: 'shingu-3aced',
    storageBucket: 'shingu-3aced.firebasestorage.app',
    iosClientId: '51232428753-2s3d7hdau9e9ea85504s6juiu1omq8o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNH1S1_NE02d6LzS3Gn4Nio6ef2Jtf6u0',
    appId: '1:51232428753:web:98463126bc7d138f6bebf0',
    messagingSenderId: '51232428753',
    projectId: 'shingu-3aced',
    authDomain: 'shingu-3aced.firebaseapp.com',
    storageBucket: 'shingu-3aced.firebasestorage.app',
    measurementId: 'G-2KFBKZ3Q9L',
  );
}
